### ISSUE TITLE
This one ebook doesn't read...

### ISSUE THREAD

**Issue by pedasmith** [asido/EpubSharp#8]
https://1drv.ms/u/s!AjG9pmUcv66_ts8zXPWPprsz8L-sug?e=NfR7fl

Throws exception System.FormatException: 'Input string was not in a correct format.'
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Xml.Linq.XAttribute.op_Explicit(XAttribute attribute)
   at EpubSharp.Format.Readers.NcxReader.<>c.<Read>b__0_1(XElement elem)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EpubSharp.Format.Readers.NcxReader.Read(XDocument xml)
   at EpubSharp.EpubReader.Read(Stream stream, Boolean leaveOpen)
   at SimpleEpubReader.FileWizards.GutenbergFileWizard.<GetDataAsync>d__0.MoveNext() in C:\Users\toomr\source\repos\SimpleEpubReader\SimpleEpubReader\FileWizards\GutenbergFileWizard.cs:line 50

This is somewhat random ebook I grabbed in order to test your library in my new ebook reader. So far, most ebooks area read by your library perfectly (testing includes books from the UN, USDA, NASA, Project Gutenberg and archive.org, plus others as I find them)

Other ebook readers (Nook and Freda) can read it OK.

**Comment by asido** [comment]
Fixed in #9.
